package com.faithbj.oauth.as.domain;

import java.io.Serializable;
import java.util.Date;

public class OauthApprovals implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.userId
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.clientId
     *
     * @mbg.generated
     */
    private String clientid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.scope
     *
     * @mbg.generated
     */
    private String scope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.expiresAt
     *
     * @mbg.generated
     */
    private Date expiresat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.lastModifiedAt
     *
     * @mbg.generated
     */
    private Date lastmodifiedat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth_approvals
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.userId
     *
     * @return the value of oauth_approvals.userId
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.userId
     *
     * @param userid the value for oauth_approvals.userId
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.clientId
     *
     * @return the value of oauth_approvals.clientId
     *
     * @mbg.generated
     */
    public String getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.clientId
     *
     * @param clientid the value for oauth_approvals.clientId
     *
     * @mbg.generated
     */
    public void setClientid(String clientid) {
        this.clientid = clientid == null ? null : clientid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.scope
     *
     * @return the value of oauth_approvals.scope
     *
     * @mbg.generated
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.scope
     *
     * @param scope the value for oauth_approvals.scope
     *
     * @mbg.generated
     */
    public void setScope(String scope) {
        this.scope = scope == null ? null : scope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.status
     *
     * @return the value of oauth_approvals.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.status
     *
     * @param status the value for oauth_approvals.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.expiresAt
     *
     * @return the value of oauth_approvals.expiresAt
     *
     * @mbg.generated
     */
    public Date getExpiresat() {
        return expiresat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.expiresAt
     *
     * @param expiresat the value for oauth_approvals.expiresAt
     *
     * @mbg.generated
     */
    public void setExpiresat(Date expiresat) {
        this.expiresat = expiresat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.lastModifiedAt
     *
     * @return the value of oauth_approvals.lastModifiedAt
     *
     * @mbg.generated
     */
    public Date getLastmodifiedat() {
        return lastmodifiedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.lastModifiedAt
     *
     * @param lastmodifiedat the value for oauth_approvals.lastModifiedAt
     *
     * @mbg.generated
     */
    public void setLastmodifiedat(Date lastmodifiedat) {
        this.lastmodifiedat = lastmodifiedat;
    }
}