package com.faithbj.oauth.as.domain;

import java.io.Serializable;

public class OauthRefreshTokenWithBLOBs extends OauthRefreshToken implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_refresh_token.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_refresh_token.authentication
     *
     * @mbg.generated
     */
    private String authentication;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth_refresh_token
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_refresh_token.token
     *
     * @return the value of oauth_refresh_token.token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_refresh_token.token
     *
     * @param token the value for oauth_refresh_token.token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_refresh_token.authentication
     *
     * @return the value of oauth_refresh_token.authentication
     *
     * @mbg.generated
     */
    public String getAuthentication() {
        return authentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_refresh_token.authentication
     *
     * @param authentication the value for oauth_refresh_token.authentication
     *
     * @mbg.generated
     */
    public void setAuthentication(String authentication) {
        this.authentication = authentication == null ? null : authentication.trim();
    }
}