package com.faithbj.oauth.as.mapper;

import com.faithbj.oauth.as.domain.TbRoles;
import com.faithbj.oauth.as.domain.TbRolesCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    long countByExample(TbRolesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    int deleteByExample(TbRolesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    int insert(TbRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    int insertSelective(TbRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    List<TbRoles> selectByExample(TbRolesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    TbRoles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbRoles record, @Param("example") TbRolesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbRoles record, @Param("example") TbRolesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbRoles record);
}